import type { Metadata } from "next";
import { /*EffectsOverlay,*/ Hud, Background, SVGFilters, Meta } from "@/components";
import { WindowFrameStyle } from "@/components/Window/Window";

// import { backgroundPortalAtom } from "@/atoms/portalAtoms";
import Fonts from "@/components/Fontst/Fonts";
import Grid from "@/components/Grid/Grid";
import LayoutCube from "@/components/LayoutCube/LayoutCube";

import "@/styles/base.css";
import styles from "./layout.module.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Fonts />
      <WindowFrameStyle />
      <body className={`${styles.pixelMask} ${styles.body}`}>
        <Grid />
        <main className={styles.rootLayout}>
          {children}
        </main>
        {/* <EffectsOverlay /> */}
        <Background />
        <Hud />
        {/* <Terminal /> */}
        <SVGFilters />
        <Meta />
      </body>
    </html>
  );
}
